tree-sitter-langs-build.el

I ran into this issue when manually building the language grammars for Apple Silicon. As I built the language grammar manually, I had to create my own BUNDLE-VERSION file so that `tree-sitter-langs-install-grammar` would not override my build. 
But as BUNDLE-VERSION was manually created, it was terminated with a `\n`. This causes the version comparison to fail because "v0.10.0" != "v0.10.0\n". This fix trims the version string before comparing.

Trim version string before comparing in tree-sitter-langs-install-grammar

---

.gitmodules
queries/pgn/highlights.scm
tree-sitter-langs.el

Not a programming language!  But it works just the same.
The intention is for [pygn-mode](https://github.com/dwcoates/pygn-mode) to depend on emacs-tree-sitter.
cc @dwcoates
Edit: direct link to the PGN grammar: https://github.com/rolandwalker/tree-sitter-pgn

Add support for chess Portable Game Notation (PGN)

---

.gitmodules
queries/hcl/highlights.scm
tree-sitter-langs.el

Adding support for HCL highlighting. This can additionally be used by other HCL based config (Terraform, Vault, etc) but currently doesn't have additionally highlighting for missing keywords for those specific products.

Add HCL support

---

queries/ruby/highlights.scm

This largely steals the highlighting rules used by neovim.
They have more specific rules and have different features
implemented so some modifications were made. There are differences
in how the different implementations handle the queries as well.
Overall this adds additional highlighting that the default ruby
highlight queries achieve via local information and the not-in
predicate.

Update Ruby highlighting

---

.azure-pipelines/main.yml
.github/workflows/main.yml
.github/workflows/release.yml
.gitmodules

LetsEncrypt's new root CA cert `ISRG Root X1` is not as widely accepted as it should be yet. Some examples:
- The Emacs 27.2 archive for Windows on FTP probably includes an outdated bundle of root CA certs. See also https://github.com/jcs090218/setup-emacs-windows/issues/156
- Several hosted runners on GitHub Actions and Azure Pipelines.
This PR adds a bunch of workarounds.
One of them is switching janet-simple's git url from codeberg.org to github.com, FYI @sogaiu.
References:
- https://docs.certifytheweb.com/docs/kb/kb-202109-letsencrypt/
- https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Fix CI issues caused by new LetsEncrypt root CA cert

---

.gitmodules

The current elixir submodule has been archived as the Elixir team has their own tree-sitter grammar. This PR just points at the new repo. I'm not so confident with submodules, so if there is anything else that needs to be done let me know. 
Also, I believe the Elisp just pulls in the `queries/highlights.scm` so this should just work?

Update Elixir grammar to official Elixir-lang repo

---

.gitmodules
tree-sitter-langs.el

I'm trying to add support for [the D programming language](https://dlang.org) via https://github.com/CyberShadow/tree-sitter-d. But when I then do
```sh
script/compile d
```
on this branch it fails as
```
script/compile: line 13: cd: $'/home/per/Work/tree-sitter-langs/script\n/home/per/Work/tree-sitter-langs/script/..': No such file or directory
[tree-sitter-langs] Processing d
Debugger entered--Lisp error: (error "Unknown language `d'")
signal(error ("Unknown language `d'"))
error("Unknown language `%s'" d)
(if source (file-name-as-directory (concat (tree-sitter-langs--repos-dir) (symbol-name lang-symbol))) (error "Unknown language `%s'" lang-symbol))
(let* ((source (tree-sitter-langs--source lang-symbol)) (dir (if source (file-name-as-directory (concat (tree-sitter-langs--repos-dir) …
```

Add D support

---

queries/ruby/highlights.scm

Hello! I wasn't sure if I should raise an issue, but the code for this change seemed simple enough, so here it is! Let me know if there's a more helpful way for me to raise this issue.
---
This treats assignment to a list of variables in the same was as regular
assignment. Prior to this change assignment to a list of identifiers
would be highlighted the same way as references to those identifiers.
Before this change:
And after:

Include left_assignment_list in ruby query

---

queries/javascript/highlights.scm

Closes https://github.com/emacs-tree-sitter/elisp-tree-sitter/issues/187

js/ts | fix highlighting of template string embedded expressions

---

queries/ruby/highlights.scm

There are two syntaxes for defining "blocks" in ruby. One is to use "do"
and "end" to mark the start and end of a block, the other is to use "{"
and "}". These are used almost identically and so they should be
highlighted in the same way.
Plus, braces are also used to denote a Hash literal. For example, `{ a:
1 }` is a Hash with a key of `:a` and a value of 1, while `{ :a }` is a
block that just yields `:a`. This change allows those two different use
cases to be visually distinguished.
---
Before this change, brace blocks were highlighted differently from `do...end` blocks and the same as `Hash`es:
After this change, the brace blocks are highlighted the same as `do...end` blocks and are distinguishable from `Hash`es:

Highlight ruby block delimiters consistently

---

CHANGELOG.md
tree-sitter-langs-build.el

Make grammar installation download platform-specific binaries

---

CHANGELOG.md
queries/cpp/highlights.scm

Hello!:)
**Reason for updating:** nested namespace definition support; the old grammar handles it miserably.
**Reason for modifying the highlighting config**: breaking changes in https://github.com/tree-sitter/tree-sitter-cpp/pull/133
**I did not test this thoroughly**; just viewed a .cpp file with `tree-sitter-hl-mode` and `tree-sittter-debug-mode` enabled and observed the lack of errors. `script/test cpp` fails with the message "Cannot open load file: No such file or directory, tree-sitter".

Bump C++ grammar

---

.gitmodules
CHANGELOG.md
README.org
queries/hcl/highlights.scm
queries/hcl/highlights.terraform-mode.scm
tree-sitter-langs.el

- Switch to https://github.com/MichaHoffmann/tree-sitter-hcl.
- Add mode-specific highlighting patterns for `terraform-mode`.
Subsumes #85 and #97.

Improve HCL support

---

tree-sitter-langs.el

Verilog was added to repos, but was not added to `tree-sitter-major-mode-language-alist` in https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/67 .

Add verilog to `tree-sitter-major-mode-language-alist`

---

queries/java/highlights.scm

Bumping java grammar to latest primarily for https://github.com/tree-sitter/tree-sitter-java/commit/a24ae7d16de3517bff243a87d087d0b4877a65c5
ref: https://github.com/meain/evil-textobj-tree-sitter/issues/54

Bump java grammar

---

queries/c/highlights.scm

Super simple PR, just added the `goto` keyword to the keyword array in the C language highlight.scm queries file.

Add the 'goto' keyword in C

---

queries/yaml/highlights.scm

Queries cover all YAML features, and results in nearly identical syntax highlighting colors as yaml-mode itself.
---
Due to no movement on #129 for a while, I decided to try my hand at a more comprehensive set of highlight queries. Hence this is based on @nossralf's changes in #129 and @meain's comment on it.
Main differences to how yaml-mode highlights:
- Integers and floats are highlighted as numbers.
- Multi-line text blocks are correctly highlighted, resolving issued I've had with yaml-mode (example in screenshots below).
These screenshots are both with the doom-vibrant theme.
**tree-sitter highlighting**:
**yaml-mode highlighting**:
The yaml file from the screenshots:
<details>
<summary><code>yaml-demo.yml</code></summary>
```yaml
%TAG !py! tag:yaml.org,2002:python/object:hello
--- …
```

feat(highlight/yaml): add comprehensive yaml highlight queries

---

tree-sitter-langs.el

The mode is called `agda2-mode` (see https://agda.readthedocs.io/en/latest/tools/emacs-mode.html).

Fix agda-mode => agda2-mode

---

queries/haskell/highlights.scm

The order of the highlights messed up the variable highlighting and everything was highlighting very weirdly. This PR fixes some of that weirdness.
Here's an example of how the highlighting used to look:
And how it looks now:

Reordered and modified Haskell highlights.

---

CHANGELOG.md

Me again. The "fuzzer" found problems in the code that caused hangs and sigsegvs. They were related mostly to baddly handled UTF-8 chars in my code (and the sigsegv came from the stdlib O.o). Now fixed. It now ran for 1 hour without finding any more problems so hopefully there's nothing like that anymore.

Bump matlab grammar

---

.gitmodules
CHANGELOG.md
tree-sitter-langs.el

Following the [readme](https://github.com/emacs-tree-sitter/tree-sitter-langs#adding-a-new-grammar) and mirroring a similar PR (#165).
Compiled and tested against tree-sitter `0.19.5`.
Also tested locally, driving `tree-sitter-indent-mode`

feat: Add Smithy support

---

queries/bibtex/highlights.scm

add missing highlights.scm for bibtex which is from [latex-lsp/tree-sitter-bibtex](https://github.com/latex-lsp/tree-sitter-bibtex).

fix(bibtex): add highlights.scm

---

tree-sitter-langs-build.el

- Adds feature for auto-installing latest tree-sitter-langs grammar.
- Simplifies the update process, ensuring easy access to the latest grammars.

feat: Implement Automatic Latest Version Installation for tree-sitter-langs

---

script/compile

If 'LANG' is set to 'pascal' in script/compile, when `emacs -Q ...` is launcher emacs will exit with the following error:
Language environment not defined: "Punjabi"
This is because 'LANG' is a locale setting variable so 'pascal' is interpreted as 'pa' which is code for the Punjabi locale.
fixes emacs-tree-sitter/tree-sitter-langs#283

Rename 'LANG' variable in script/compile to avoid bug.

---

tree-sitter-langs-build.el

Currently, to run on FreeBSD you need to:
install cask, npm and cargo.
launch:
cargo install tree-sitter-cli
For npm, as the tgz doesn't exist for the moment you have to create a node_modules/tree-sitter-cli directory and copy the cli.js, dsl.d.ts, install.js, package.json, LICENSE files from the official tree-sitter/cli/npm/tree-sitter repository and also tree-sitter from the directory where cargo installed the binary
Of course you have to add ('berkeley-unix (list ".so")) in elisp-tree-sitter/lisp/tree-sitter-load.el to be able to load the .so
and that's it
If the FreeBSD build becomes integrated by default, all the prerequisites become superfluous

Add FreeBSD support

---

.gitmodules
tree-sitter-langs-build.el

fix: update markdown submodule link

---

tree-sitter-langs-build.el

This change allows the package to work on Emacs on Android + termux.
Users will still need to manually install the required termux packages.
A change to the `tree-sitter` package is also needed for things to work locally (see https://github.com/emacs-tree-sitter/elisp-tree-sitter/pull/280).

Add support for Android (with termux)

---

queries/python/highlights.scm

This fixes python highlighting for docstrings, f-strings, and escape sequences.
---
Closes #169

fix(python): properly highlight docstrings, f-strings, and escapes

---

queries/r/highlights.scm
queries/r/locals.scm
queries/r/tags.scm

This PR updates the R queries to be the same as those in r-lib/tree-sitter-r.
Note that I *think* the tuning done here:
https://github.com/emacs-tree-sitter/tree-sitter-langs/blob/7007cbcd5ab16d01aada410bfbe6ecc626ae838f/queries/r/highlights.scm#L17-L24
was accounted for in the latest queries, but I'm not positive.
Closes #735

fix: update r queries

---

queries/r/highlights.scm

As per Emacs' highlighting conventions ([here](https://emacs-tree-sitter.github.io/syntax-highlighting/)), special faces should have higher priority than more general ones. This lowers the priority of the more general `variable` face. Additionally, it only highlights `variable` when assigned (with `<-` or `=`), and not otherwise.

fix: R: Conform to Emacs highlighting conventions

---

.gitmodules
queries/zig/highlights.scm

Got these from nvim-treesitter
- https://github.com/nvim-treesitter/nvim-treesitter

feat(queries): Update Zig highlights scm

---

tree-sitter-langs-build.el

Add support for AArch64 FreeBSD so that it doesn't incorrectly get recognised as x86_64 FreeBSD.

build: Support AArch64 FreeBSD
