emacs-tree-sitter/tree-sitter-langs

- queries/python/highlights.scm
Should fix https://github.com/ubolonton/tree-sitter-langs/issues/4
> treat raw docstring as docstring

- queries/tsx/highlights.scm
- tree-sitter-langs.el
https://github.com/ubolonton/emacs-tree-sitter/issues/66#issuecomment-786959909
> Add simple highlight for tsx file

- queries/json/highlights.scm
Just drag the `highlights.scm` file from upstream. https://github.com/tree-sitter/tree-sitter-json
Tested and it works!
> Add JSON highlights.scm

- queries/bash/highlights.scm
Tested, and it works! 😁 
Drag from the upstream https://github.com/tree-sitter/tree-sitter-bash
> Add Bash highlights.scm

- CHANGELOG.md
> Bump java parser (#52)

- .gitmodules
- tree-sitter-langs.el
> Add nix support

- CHANGELOG.md
- queries/python/highlights.scm
> Update python grammar

- .gitmodules
- CHANGELOG.md
- tree-sitter-langs.el
This PR add support for [zig](http://ziglang.org) using https://github.com/maxxnino/tree-sitter-zig
> Add zig support

- CHANGELOG.md
Fix #90, update javascript parser to fix parsing object destructing with default values.
Update typescript parser as well to make sure it's compatible with the javascript parser it depends on.
> Update javascript, typescript parsers.

- .gitmodules
- CHANGELOG.md
- tree-sitter-langs.el
https://github.com/ikatyang/tree-sitter-yaml
This adds yaml grammar (no highlights).
> Add yaml grammar

- CHANGELOG.md
- queries/haskell/highlights.scm
- tree-sitter-langs.el
Just little edit to improve Haskell support.
> Add haskell-mode and highlights.scm

- .gitmodules
- CHANGELOG.md
- tree-sitter-langs.el
Don't know if this actually contains all the necessary changes, just followed the docs.
> Add perl grammar

- CHANGELOG.md
- queries/go/highlights.scm
Fixes issue with parsing generics
> Bump go grammar

- .gitmodules
- CHANGELOG.md
- tree-sitter-langs.el
Based on https://github.com/WhatsApp/tree-sitter-erlang
> Add Erlang support

- .gitmodules
- CHANGELOG.md
- queries/r/highlight.scm
- queries/r/locals.scm
- tree-sitter-langs.el
I use the original work from the PRs https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/45 (Jen-Chieh Shen, @jcs090218, jcs090218@gmail.com) and https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/104 (Shuguang Sun, @ShuguangSun, shuguang79@qq.com); rebased against master and updated the submodule to the latest version.
Also, I added a changelog entry.
> Add R support

- .gitmodules
- CHANGELOG.md
- queries/lua/highlights.scm
- tree-sitter-langs.el
I did mess a lot with the queries until I reached feature-parity with the Python queries, by eye at least.
> Lua support

- .github/workflows/main.yml
https://github.com/actions/virtual-environments/issues/5583
> Update CI matrix

- CHANGELOG.md
- script/test
- script/test.ps1
Hoping this would fix CI issues.
> Bump typescript grammar

- CHANGELOG.md
- queries/go/highlights.scm
Overrides https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/142 , fixes https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/145
> Fix go highlights

- .gitmodules
- tree-sitter-langs.el
This implementation is the one listed in the official tree-sitter website.
> Add Markdown support

- .github/workflows/bump-version.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
Fixes https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/162
> Use ubuntu-20.04 in CI jobs

- .gitmodules
- CHANGELOG.md
- tree-sitter-langs.el
followed readme. Compiled and passed tests with tree-sitter 0.20.7
> add clojure grammar

- .gitmodules
- CHANGELOG.md
- tree-sitter-langs.el
Followed readme to add the grammar. Compiled and passed all tests on treesitter 0.20.7.
> Add fennel grammar

- queries/elixir/highlights.scm
Follow up on https://github.com/emacs-tree-sitter/tree-sitter-langs/pull/57#issuecomment-1382667258
jFYI @meain @jsmestad
> Rebase PR #57 – Add Elixir highlight query

- .gitmodules
- CHANGELOG.md
- tree-sitter-langs.el
Following README instructions.
> Add meson grammar

- .github/workflows/bump-version.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
- Eask
- README.org
- script/bundle-version
- script/bundle-version.ps1
- script/test
- script/test.ps1
For #178.
@meain I know you would like to avoid CI changes if possible (https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/154#issuecomment-1368714544), so feel free to close this PR.
**Intention:** It seems like @ubolonton is busy and not able to respond. 🤔 So I've opened this PR so we don't block the development due to the build tool (Cask).
See log: https://github.com/jcs-PR/tree-sitter-langs/actions/runs/5296926346 (it's all green ✅)
> ci: Build with Eask

- CHANGELOG.md
Unblocks https://github.com/meain/scopeline.el/pull/11 and https://github.com/emacs-tree-sitter/ts-fold/pull/37
> Bump nix grammar

- .github/workflows/release.yml
- .gitignore
- Eask
See full log: https://github.com/jcs-PR/tree-sitter-langs/actions/runs/5329926270.
> ci: Fix release

- CHANGELOG.md
- queries/cpp/highlights.scm
> Bump C++ grammar

- .gitmodules
- tree-sitter-langs.el
Need this to add folding in [ts-fold](https://github.com/emacs-tree-sitter/ts-fold).
> feat: Add Elisp support

- queries/dart/highlights.scm
> fix: Dart highlight.scm

- .gitmodules
- CHANGELOG.md
- queries/pascal/highlights.scm
- tree-sitter-langs.el
> feat: Add Pascal support

- CHANGELOG.md
Try to solve the following error. 🤔 
```
Test queries/tsx backtrace:
tsc--load-language("d:/a/tree-sitter-langs/tree-sitter-langs/bin/tsx
tree-sitter-load(tsx nil nil)
tree-sitter-require(tsx)
(let ((language (tree-sitter-require lang-symbol)) (patterns (tree-s
tree-sitter-langs-tests-check-queries(tsx)
(lambda nil (tree-sitter-langs-tests-check-queries 'tsx))()
ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
ert-run-test(#s(ert-test :name queries/tsx :documentation nil :body 
ert-run-or-rerun-test(#s(ert--stats :selector t :tests [... ... ... 
ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
ert-run-tests-batch(nil)
ert-run-tests-batch-and-exit(nil)
eval((ert-run-tests-batch-and-exit nil) t)
command-line-1(("-l" …
```
> Bump TypeScript/TSX grammar

- .gitmodules
- CHANGELOG.md
- tree-sitter-langs-tests.el
- tree-sitter-langs.el
For #158. Try once again.
Last attempt #235.
> feat: Add Fortran support

- .gitmodules
- CHANGELOG.md
- queries/mermaid/highlights.scm
- tree-sitter-langs.el
> feat: Add Mermaid support

- .gitmodules
- CHANGELOG.md
- queries/solidity/highlights.scm
- tree-sitter-langs.el
> feat: Add Solidity support

- .gitmodules
- CHANGELOG.md
- queries/heex/highlights.scm
- tree-sitter-langs.el
> feat: Add HEEx support

- .gitmodules
- CHANGELOG.md
- tree-sitter-langs.el
> feat: Add magik grammar

- tree-sitter-langs.el
> Bug 442 cperl

- .github/workflows/update-grammars.yml
Add markdown and markdown-inline to updating workflows.
> ci: add markdown and markdown-inline to updating workflows

- queries/nix/highlights.scm
Grabbed from the main repo, https://github.com/nix-community/tree-sitter-nix/.
> feat(queries): Add Nix highlights.scm

- .github/workflows/main.yml
- .github/workflows/release.yml
See https://github.com/actions/runner-images/issues/10721.
> fix: macos-12 deprecation

- .github/workflows/main.yml
- .github/workflows/release.yml
- tree-sitter-langs-build.el
Closes https://github.com/emacs-tree-sitter/tree-sitter-langs/issues/305.
> ci: cross-compiling to aarch64-unknown-linux-gnu on GitHub Actions
